"""
Decision Generator - FINAL CORRIGÉ
===================================
Répond dans la langue du patient (FR/EN/AR/ES)
"""

from typing import Dict, List


class DecisionGenerator:
    """Génère des rapports médicaux dans la langue du patient"""
    
    def __init__(self, patient_country: str = "Tunisie", patient_city: str = None):
        self.patient_country = patient_country
        self.patient_city = patient_city
        
        # Numéros d'urgence
        self.emergency_numbers = {
            'Tunisie': {'samu': '190', 'urgences': '197', 'police': '197', 'pompiers': '198'},
            'France': {'samu': '15', 'urgences': '112', 'police': '17', 'pompiers': '18'},
            'Maroc': {'samu': '150', 'urgences': '141', 'police': '19', 'pompiers': '15'},
        }
        
        # Traductions des labels
        self.translations = {
            'en': {
                'medical_report': 'MEDICAL REPORT',
                'patient_info': 'PATIENT INFORMATION',
                'symptoms_reported': 'Reported symptoms',
                'country': 'Country',
                'city': 'City',
                'medical_analysis': 'MEDICAL ANALYSIS',
                'probable_diagnosis': 'Probable diagnosis',
                'urgency_level': 'Urgency level',
                'confidence_level': 'Confidence level',
                'specialist_recommended': 'RECOMMENDED SPECIALIST',
                'consultation': 'Consultation',
                'recommended_delay': 'Recommended delay',
                'action': 'Action',
                'emergency_numbers': 'EMERGENCY NUMBERS',
                'samu_ambulance': 'SAMU / Ambulance',
                'medical_emergencies': 'Medical emergencies',
                'police': 'Police',
                'firefighters': 'Firefighters',
                'recommendations': 'RECOMMENDATIONS',
                'warning_signs': 'WARNING SIGNS - Consult immediately if',
                'in_this_case_call': 'In this case, call',
                'when_to_consult': 'WHEN TO CONSULT',
                'this_report_automated': 'This report is automatically generated by AI',
                'not_replace_doctor': 'It does not replace the advice of a healthcare professional',
                'if_in_doubt': 'If in doubt, consult a doctor',
            },
            'fr': {
                'medical_report': 'RAPPORT MÉDICAL',
                'patient_info': 'INFORMATIONS PATIENT',
                'symptoms_reported': 'Symptômes rapportés',
                'country': 'Pays',
                'city': 'Ville',
                'medical_analysis': 'ANALYSE MÉDICALE',
                'probable_diagnosis': 'Diagnostic probable',
                'urgency_level': 'Niveau d\'urgence',
                'confidence_level': 'Niveau de confiance',
                'specialist_recommended': 'SPÉCIALISTE RECOMMANDÉ',
                'consultation': 'Consultation',
                'recommended_delay': 'Délai recommandé',
                'action': 'Action',
                'emergency_numbers': 'NUMÉROS D\'URGENCE',
                'samu_ambulance': 'SAMU / Ambulance',
                'medical_emergencies': 'Urgences médicales',
                'police': 'Police',
                'firefighters': 'Pompiers',
                'recommendations': 'RECOMMANDATIONS',
                'warning_signs': 'SIGNES D\'ALERTE - Consulter immédiatement si',
                'in_this_case_call': 'Dans ce cas, appeler le',
                'when_to_consult': 'QUAND CONSULTER',
                'this_report_automated': 'Ce rapport est généré automatiquement par IA',
                'not_replace_doctor': 'Il ne remplace pas l\'avis d\'un professionnel de santé',
                'if_in_doubt': 'En cas de doute, consultez un médecin',
            }
        }
    
    def generate_decision(self, reasoning: Dict) -> str:
        """Génère un rapport dans la langue du patient"""
        
        # Détecter la langue du patient
        language = reasoning.get('language', 'fr')
        if language not in ['en', 'fr']:
            language = 'en'
        
        # Extraire les infos
        symptoms = reasoning.get('symptoms', [])
        disease = reasoning.get('disease', 'Unknown' if language == 'en' else 'Inconnu')
        urgency = reasoning.get('urgency', 'URGENCE MODÉRÉE')
        confidence = reasoning.get('confidence', 50.0) / 100 if reasoning.get('confidence', 50.0) > 1 else reasoning.get('confidence', 0.5)
        specialist = reasoning.get('specialist', 'General practitioner' if language == 'en' else 'Médecin généraliste')
        timing = reasoning.get('timing', '24-48 hours' if language == 'en' else '24-48 heures')
        recommendations = reasoning.get('recommendations', [])
        
        # Traduire
        t = self.translations[language]
        
        # Construire le rapport
        lines = []
        
        # En-tête
        lines.append("")
        lines.append("╔" + "═"*68 + "╗")
        lines.append("║" + t['medical_report'].center(68) + "║")
        lines.append("╚" + "═"*68 + "╝")
        lines.append("")
        
        # Patient
        lines.append(f"👤 {t['patient_info']}")
        lines.append("─" * 70)
        
        symptom_names = [s.get('symptom', '') for s in symptoms if isinstance(s, dict)]
        if not symptom_names and isinstance(symptoms, list):
            symptom_names = [str(s) for s in symptoms]
        
        symptom_text = ', '.join(symptom_names[:5]) if symptom_names else ("Not specified" if language == 'en' else "Non spécifié")
        lines.append(f"   {t['symptoms_reported']}: {symptom_text}")
        lines.append(f"   {t['country']}: {self.patient_country}")
        if self.patient_city:
            lines.append(f"   {t['city']}: {self.patient_city}")
        lines.append("")
        
        # Diagnostic
        lines.append(f"🏥 {t['medical_analysis']}")
        lines.append("─" * 70)
        lines.append(f"   {t['probable_diagnosis']}: {disease}")
        lines.append(f"   {t['urgency_level']}: {urgency}")
        lines.append(f"   {t['confidence_level']}: {confidence:.0%}")
        lines.append("")
        
        # Spécialiste
        lines.append(f"⚕️  {t['specialist_recommended']}")
        lines.append("─" * 70)
        lines.append(f"   {t['consultation']}: {specialist}")
        lines.append(f"   {t['recommended_delay']}: {timing}")
        
        action_text = 'Make appointment quickly' if language == 'en' else 'Prendre rendez-vous rapidement'
        lines.append(f"   {t['action']}: {action_text}")
        lines.append("")
        
        # Urgence
        lines.append(f"🚨 {t['emergency_numbers']} ({self.patient_country.upper()})")
        lines.append("─" * 70)
        
        emergency_nums = self.emergency_numbers.get(self.patient_country, self.emergency_numbers.get('Tunisie'))
        
        lines.append(f"   {t['samu_ambulance']}: {emergency_nums.get('samu', '190')}")
        lines.append(f"   {t['medical_emergencies']}: {emergency_nums.get('urgences', '190')}")
        lines.append(f"   {t['police']}: {emergency_nums.get('police', '197')}")
        lines.append(f"   {t['firefighters']}: {emergency_nums.get('pompiers', '198')}")
        lines.append("")
        
        # Recommandations
        if recommendations:
            lines.append(f"💊 {t['recommendations']}")
            lines.append("─" * 70)
            for i, rec in enumerate(recommendations, 1):
                lines.append(f"   {i}. {rec}")
            lines.append("")
        
        # Signes d'alerte
        warning_signs = [
            'Aggravation rapide des symptômes' if language == 'fr' else 'Rapid worsening of symptoms',
            'Douleur qui s\'intensifie' if language == 'fr' else 'Intensifying pain',
            'Fièvre persistante > 48h' if language == 'fr' else 'Persistent fever > 48h',
            'Vomissements répétés' if language == 'fr' else 'Repeated vomiting',
            'Impossibilité de s\'alimenter ou boire' if language == 'fr' else 'Inability to eat or drink',
        ]
        
        lines.append(f"⚠️  {t['warning_signs']}:")
        lines.append("─" * 70)
        for sign in warning_signs:
            lines.append(f"   • {sign}")
        lines.append(f"   → {t['in_this_case_call']} {emergency_nums.get('samu', '190')}")
        lines.append("")
        
        # Quand consulter
        lines.append(f"⏰ {t['when_to_consult']}")
        lines.append("─" * 70)
        
        if 'VITALE' in urgency or 'VITAL' in urgency or 'ÉLEVÉE' in urgency or 'HIGH' in urgency:
            consult_text = 'Today or tomorrow - Make appointment quickly' if language == 'en' else 'Aujourd\'hui ou demain - Prendre rendez-vous rapidement'
            lines.append(f"   📍 {consult_text}")
        else:
            consult_text = 'This week - Non-urgent consultation' if language == 'en' else 'Cette semaine - Consultation non urgente'
            lines.append(f"   📍 {consult_text}")
        
        lines.append(f"   ⏱️  {timing}")
        lines.append("")
        
        # Pied de page
        lines.append("─" * 70)
        lines.append(f"ℹ️  {t['this_report_automated']}")
        lines.append(f"   {t['not_replace_doctor']}")
        lines.append(f"   {t['if_in_doubt']}")
        lines.append("─" * 70)
        lines.append("")
        
        return "\n".join(lines)